apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPSPHostFilesystem
metadata:
  name: psp-host-filesystem
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    excludedNamespaces:
    - velero
    - openebs
    - grafana-agent
    - system-upgrade
    - kube-system
  parameters:
    allowedHostPaths: []
