apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: radarr
  labels:
    app.kubernetes.io/name: radarr
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - radarr.joshcorp.co
    secretName: radarr-joshcorp-tls
  rules:
  - host: radarr.joshcorp.co
    http:
      paths:
      - backend:
          serviceName: radarr
          servicePort: http
        path: /