apiVersion: v1
kind: PersistentVolume
metadata:
  name: sichy
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 100.91.81.36
    path: "/sichy"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-sichy
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "manual"
  volumeName: sichy
  resources:
    requests:
      storage: 1Mi
