apiVersion: v1
kind: PersistentVolume
metadata:
  name: speicher
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 100.71.44.76
    path: "/speicher"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-speicher
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "manual"
  volumeName: speicher
  resources:
    requests:
      storage: 1Mi
