apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sonarr
  labels:
    app.kubernetes.io/name: sonarr
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - sonarr.joshcorp.co
    secretName: sonarr-joshcorp-tls
  rules:
  - host: sonarr.joshcorp.co
    http:
      paths:
      - backend:
          serviceName: sonarr
          servicePort: http
        path: /