---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett
  labels:
    app: jackett
    app.kubernetes.io/name: jackett
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jackett
  labels:
    app: jackett
    app.kubernetes.io/name: jackett
spec:
  selector:
    app.kubernetes.io/name: jackett
  ports:
  - name: http
    port: 80
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: jackett
    app.kubernetes.io/name: jackett
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: jackett
  template:
    metadata:
      labels:
        app: jackett
        app.kubernetes.io/name: jackett
    spec:
      nodeSelector:
        storagespeed: slow
      containers:
      - name: jackett
        image: linuxserver/jackett
        env:
        - name: TZ
          value: America/Chicago
        volumeMounts:
          - name: jackett-config
            mountPath: /config
          - name: media
            mountPath: /downloads
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
        livenessProbe:
            tcpSocket:
              port: http
            failureThreshold: 5
            periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: http
          failureThreshold: 5
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 10
        ports:
        - name: http
          containerPort: 9117
      - name: vpn
        image: dperson/openvpn-client
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - '[ "$(curl -s https://ifconfig.co/city)" != "Austin" ]'
          initialDelaySeconds: 30
          periodSeconds: 60
        envFrom:
        - secretRef:
            name: vpn-config
        env:
        - name: FIREWALL
          value: "on"
        - name: ROUTE
          value: 10.0.0.0/8
        volumeMounts:
          - name: vpn-config
            mountPath: /vpn
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
      volumes:
      - name: jackett-config
        persistentVolumeClaim:
            claimName: jackett
      - name: media
        emptyDir: {}
      - name: vpn-config
        secret:
          secretName: vpn-config
