# helm template cilium cilium/cilium --version 1.10.3 --namespace kube-system -f networking/cilium-values.yaml > networking/cilium.yaml

nodePort:
  enabled: true
externalIPs:
  enabled: true

ipam:
  operator:
    clusterPoolIPv4PodCIDR: "10.42.0.0/16"

operator:
  replicas: 1

hubble:
  ui:
    enabled: true
  relay:
    enabled: true
