apiVersion: v1
kind: PersistentVolume
metadata:
  name: adel-plex
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /var/lib/plex
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - adel
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-austin
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  volumeName: adel-plex
  resources:
    requests:
      storage: 100Gi
