apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fathom
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kasuboski/k8s-gitops.git
    targetRevision: master
    path: fathom
  destination:
    server: https://kubernetes.default.svc
    namespace: fathom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true