apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: indieweb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kasuboski/k8s-gitops.git
    targetRevision: master
    path: indieweb
  destination:
    server: https://kubernetes.default.svc
    namespace: indieweb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true