resources:
  - argocd-app.yaml
  - default-project.yaml
  - default-app.yaml
  - fathom-app.yaml
  - indieweb-app.yaml
  - ingress-app.yaml
  - media-app.yaml
  - policy-app.yaml
  - secrets-app.yaml
  - storage-app.yaml
  - upgrades-app.yaml