apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: miniflux
  labels:
    app.kubernetes.io/name: miniflux
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - miniflux.joshcorp.co
    secretName: miniflux-joshcorp-tls
  rules:
  - host: miniflux.joshcorp.co
    http:
      paths:
      - backend:
          serviceName: miniflux
          servicePort: http
        path: /
