# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm template ingress-nginx ingress-nginx/ingress-nginx --version 3.15.2 -f ingress/nginx-ingress-values.yaml --namespace ingress-nginx > ingress/ingress-nginx.yaml
controller:
  service:
    type: NodePort
    nodePorts:
      http: "30080"
      https: "30443"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false