# helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
# helm install ingress-nginx ingress-nginx/ingress-nginx --version 2.1.0 -f nginx-ingress-values.yaml --namespace ingress-nginx
controller:
  service:
    type: NodePort
    nodePorts:
      http: "30080"
      https: "30443"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true