# velero install --provider aws --plugins velero/velero-plugin-for-aws:v1.1.0,openebs/velero-plugin-arm64:1.11.0 --bucket velero --secret-file creds-secret --backup-location-config region=us-west-002,s3ForcePathStyle="true",s3Url=s3.us-west-002.backblazeb2.com --snapshot-location-config region=us-west-002,s3ForcePathStyle="true",s3Url=s3.us-west-002.backblazeb2.com
apiVersion: v1
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
  spec: {}
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  subjects:
  - kind: ServiceAccount
    name: velero
    namespace: velero
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
    namespace: velero
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: velero
    namespace: velero
  spec:
    selector:
      matchLabels:
        deploy: velero
    strategy: {}
    template:
      metadata:
        annotations:
          prometheus.io/path: /metrics
          prometheus.io/port: "8085"
          prometheus.io/scrape: "true"
        creationTimestamp: null
        labels:
          component: velero
          deploy: velero
      spec:
        containers:
        - args:
          - server
          - --features=
          command:
          - /velero
          env:
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: LD_LIBRARY_PATH
            value: /plugins
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/cloud
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: ALIBABA_CLOUD_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero/velero:v1.5.1
          imagePullPolicy: IfNotPresent
          name: velero
          ports:
          - containerPort: 8085
            name: metrics
          resources:
            limits:
              cpu: "1"
              memory: 256Mi
            requests:
              cpu: 500m
              memory: 128Mi
          volumeMounts:
          - mountPath: /plugins
            name: plugins
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
          - mountPath: /etc/ssl/certs/ca-certificates.crt
            subPath: ca-certificates.crt
            name: certs
        initContainers:
        - image: raspbernetes/velero-aws-plugin:v1.1.0
          imagePullPolicy: IfNotPresent
          name: velero-plugin-for-aws
          resources: {}
          volumeMounts:
          - mountPath: /target
            name: plugins
        # - image: openebs/velero-plugin-arm64:1.11.0
        #   imagePullPolicy: IfNotPresent
        #   name: velero-plugin-arm64
        #   resources: {}
        #   volumeMounts:
        #   - mountPath: /target
        #     name: plugins
        - name: cert-copy
          image: raspbernetes/velero-aws-plugin:v1.1.0
          command: ["/bin/bash", "-c", "cp /etc/ssl/certs/ca-certificates.crt /copy/etc/ssl/ca-certificates.crt"]
          volumeMounts:
          - mountPath: /copy/etc/ssl
            name: certs
        restartPolicy: Always
        serviceAccountName: velero
        volumes:
        - name: certs
          emptyDir: {}
        - emptyDir: {}
          name: plugins
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    creationTimestamp: null
    labels:
      component: velero
    name: restic
    namespace: velero
  spec:
    selector:
      matchLabels:
        name: restic
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: velero
          name: restic
      spec:
        containers:
        - args:
          - restic
          - server
          - --features=
          command:
          - /velero
          env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: VELERO_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VELERO_SCRATCH_DIR
            value: /scratch
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /credentials/cloud
          - name: AWS_SHARED_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: AZURE_CREDENTIALS_FILE
            value: /credentials/cloud
          - name: ALIBABA_CLOUD_CREDENTIALS_FILE
            value: /credentials/cloud
          image: velero/velero:v1.5.1
          imagePullPolicy: IfNotPresent
          name: restic
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
          - mountPath: /host_pods
            mountPropagation: HostToContainer
            name: host-pods
          - mountPath: /etc/ssl/certs/ca-certificates.crt
            subPath: ca-certificates.crt
            name: certs
          - mountPath: /scratch
            name: scratch
          - mountPath: /credentials
            name: cloud-credentials
        initContainers:
        - name: cert-copy
          image: raspbernetes/velero-aws-plugin:v1.1.0
          command: ["/bin/bash", "-c", "cp /etc/ssl/certs/ca-certificates.crt /copy/etc/ssl/ca-certificates.crt"]
          volumeMounts:
          - mountPath: /copy/etc/ssl
            name: certs
        securityContext:
          runAsUser: 0
        serviceAccountName: velero
        volumes:
        - name: certs
          emptyDir: {}
        - hostPath:
            path: /var/lib/kubelet/pods
          name: host-pods
        - emptyDir: {}
          name: scratch
        - name: cloud-credentials
          secret:
            secretName: cloud-credentials
    updateStrategy: {}
kind: List

